version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_br_pizza
    restart: always
    environment:
      POSTGRES_DB: brpizza
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      
  
volumes:
  pgdata:
